# Stage 1
FROM node:18.20.3 as node
WORKDIR /app
COPY . .

# Install the Sentry CLI
RUN curl -sL https://sentry.io/get-cli/ | bash

# Accept the Sentry Auth Token as a build argument
ARG SENTRY_AUTH_TOKEN

# Setup the environment variable with the received argument
ENV SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN

# Install npm packages, including the @sentry/cli package
RUN npm install @sentry/cli
RUN npm install

# Create a symlink to replace the bundled Sentry CLI
RUN ln -sf $(which sentry-cli) /app/node_modules/@sentry/webpack-plugin/node_modules/@sentry/cli/sentry-cli

# Build the project for every language
RUN npm run build:prod:localize

# Stage 2: Setting up the server with nginx
FROM nginx:alpine

# Copy over the built English version
COPY --from=node /app/dist/chainbrary/en /usr/share/nginx/html/en

# Copy over the built French version
COPY --from=node /app/dist/chainbrary/fr /usr/share/nginx/html/fr

# Copy over the built Spanish version
COPY --from=node /app/dist/chainbrary/es /usr/share/nginx/html/es

# Copy nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
