# Stage 1
FROM node:latest as node
WORKDIR /app
COPY . .

# Install the Sentry CLI
RUN curl -sL https://sentry.io/get-cli/ | bash

# Install npm packages, including the @sentry/cli package
RUN npm install @sentry/cli
RUN npm install

# Create a symlink to replace the bundled Sentry CLI
RUN ln -sf $(which sentry-cli) /app/node_modules/@sentry/webpack-plugin/node_modules/@sentry/cli/sentry-cli

# Build the project
RUN npm run build:prod

# Stage 2
FROM nginx:alpine

# Copy build output and nginx configuration
COPY --from=node /app/dist/chain-brary /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
