version: 2
updates:
  # Enable version updates for npm on UI
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/UI"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily

  # Enable version updates for npm on SmartContracts
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/SmartContracts"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily
