version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/UI"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"

  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/SmartContracts"
    # Check for updates once a week
    schedule:
      interval: "daily"
